<script lang="ts">
	let { data, form } = $props();
</script>

<svelte:head><title>Security settings · Musha tenant portal</title></svelte:head>
<div class="shell"><header><a class="brand" href="/tenant"><img src="/logo.png" alt="Musha" /><span><strong>Musha</strong><small>Tenant portal</small></span></a><nav><span>{data.organization.name}</span><a href="/tenant">Back to portal</a><form method="POST" action="/logout"><button type="submit">Sign out</button></form></nav></header><main>{#if form?.message}<div class:failure={!form.success} class="notice">{form.message}</div>{/if}<a class="back" href="/tenant">← Back to your portal</a><section class="hero"><p>Account settings</p><h1>Keep your access secure<span>.</span></h1><span>{data.person.email ?? 'Tenant account'}</span></section><section class="card"><p class="eyebrow">Password</p><h2>Change your password</h2><p class="copy">Choose a private password of at least 8 characters. Your property manager will not be able to see it.</p><form method="POST" action="?/changePassword"><label>New password<input name="new_password" type="password" minlength="8" required autocomplete="new-password" placeholder="At least 8 characters" /></label><label>Confirm new password<input name="confirm_password" type="password" minlength="8" required autocomplete="new-password" placeholder="Repeat your new password" /></label><button type="submit">Update password <span>→</span></button></form></section></main></div>
<style>
	:global(body){background:#f7f8f5;margin:0;color:#073d3c;font-family:Inter,system-ui,sans-serif}.shell{min-height:100vh}.shell header{align-items:center;background:#fff;border-bottom:1px solid #dce6df;display:flex;justify-content:space-between;padding:12px clamp(1rem,4vw,4rem)}.brand{align-items:center;color:#073d3c;display:flex;gap:10px;text-decoration:none}.brand img{border-radius:12px;height:48px;width:48px}.brand strong,.brand small{display:block}.brand small{color:#6e8790;font-size:10px;letter-spacing:.12em;text-transform:uppercase}.shell nav{align-items:center;color:#718a82;display:flex;gap:16px;font-size:12px}.shell nav a{color:#397463;font-weight:700;text-decoration:none}.shell nav button{background:#fff;border:1px solid #d4e2d9;border-radius:8px;color:#225b56;cursor:pointer;padding:8px 11px}.shell main{margin:auto;max-width:850px;padding:48px 22px}.back{color:#417159;font-size:13px;font-weight:800;text-decoration:none}.hero{margin:42px 0 26px}.hero p,.eyebrow{color:#719082;font-size:11px;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.hero h1{color:#063f3c;font-size:clamp(38px,6vw,64px);letter-spacing:-.08em;line-height:.96;margin:10px 0}.hero h1 span{color:#b6d84a}.hero>span{color:#77938b;font-size:16px}.card{background:#fff;border:1px solid #dce9e0;border-radius:15px;padding:28px;max-width:560px}.card h2{font-size:26px;letter-spacing:-.06em;margin:5px 0}.copy{color:#6c887b;font-size:13px;line-height:1.55}.card form{display:grid;gap:14px;margin-top:22px}.card label{color:#456b5c;display:grid;font-size:12px;font-weight:800;gap:6px}.card input{border:1px solid #dce9df;border-radius:8px;background:#fbfdfb;color:#244a3b;font:inherit;padding:12px}.card button{background:#075147;border:0;border-radius:8px;color:#fff;cursor:pointer;font-weight:800;padding:13px}.card button span{color:#b6d84a;margin-left:8px}.notice{background:#e8f5df;border-radius:8px;color:#39704c;font-size:12px;margin-bottom:17px;padding:12px}.notice.failure{background:#fff0eb;color:#a35545}@media(max-width:650px){.shell nav>span{display:none}.shell main{padding:30px 16px}.card{padding:21px}}
</style>
