<script lang="ts">
	import AdminChrome from '$lib/components/AdminChrome.svelte';
	let { data, form } = $props();
	const profileFor = (organizationId: string) => data.profiles.find((profile) => profile.organization_id === organizationId);
</script>

<svelte:head><title>Operations hub · Musha platform</title></svelte:head>

<AdminChrome active="operations">
	{#if data.access === 'denied'}<section class="blocked"><h1>Platform operations access is restricted.</h1></section>{:else}
		<section class="heading"><div><p class="eyebrow">Platform command centre</p><h1>Operations hub<span>.</span></h1><p>One operational view of client health, delivery queues, product rollout, integrations, security, and platform signals.</p></div></section>
		{#if form?.message}<div class:failure={!form.success} class="notice">{form.message}</div>{/if}
		<div class="metrics"><div><span>Active clients</span><strong>{data.metrics.activeClients}</strong></div><div><span>Clients at risk</span><strong>{data.metrics.atRisk}</strong></div><div><span>Open support</span><strong>{data.metrics.openSupport}</strong></div><div><span>Queued work</span><strong>{data.metrics.queuedWork}</strong></div><div><span>Payments recorded</span><strong>{data.metrics.paidPayments}</strong></div></div>

		<div class="grid">
			<section class="panel wide"><header><div><p class="eyebrow">Client success</p><h2>Account health and renewals</h2></div><span class="count">{data.organizations.length}</span></header><div class="success-list">{#each data.organizations as organization (organization.id)}{@const profile = profileFor(organization.id)}<form method="POST" action="?/updateSuccessProfile" class="success-row"><input type="hidden" name="organization_id" value={organization.id} /><div><strong>{organization.name}</strong><small>{organization.status} · last active {organization.last_activity_at ? new Date(organization.last_activity_at).toLocaleDateString() : '—'}</small></div><label>Health<select name="health_status"><option value="healthy" selected={profile?.health_status === 'healthy'}>Healthy</option><option value="watch" selected={profile?.health_status === 'watch'}>Watch</option><option value="at_risk" selected={profile?.health_status === 'at_risk'}>At risk</option></select></label><label>Score<input name="health_score" type="number" min="0" max="100" value={profile?.health_score ?? 100} /></label><label>Next check-in<input name="next_check_in_on" type="date" value={profile?.next_check_in_on ?? ''} /></label><label>Renewal due<input name="renewal_due_on" type="date" value={profile?.renewal_due_on ?? ''} /></label><label class="notes">Risk / account note<input name="risk_notes" value={profile?.risk_notes ?? ''} placeholder="Optional internal context" /></label><button type="submit">Save</button></form>{/each}</div></section>
			<section class="panel"><header><div><p class="eyebrow">Communications</p><h2>Notification delivery</h2></div><a href="/admin/system">System health →</a></header>{#each data.notifications as notification (notification.id)}<article class="line"><div><strong>{notification.event_type}</strong><small>{notification.organizations?.[0]?.name ?? 'Platform'} · {notification.channel}</small></div><span class="badge {notification.status}">{notification.status}</span></article>{:else}<p class="empty">No recent notification activity.</p>{/each}</section>
			<section class="panel"><header><div><p class="eyebrow">Automation</p><h2>Imports and queues</h2></div><a href="/admin/imports">Imports →</a></header>{#each data.imports as job (job.id)}<article class="line"><div><strong>{job.entity_type} import</strong><small>{job.organizations?.[0]?.name ?? 'Unknown client'} · {new Date(job.created_at).toLocaleDateString()}</small></div><span class="badge {job.status}">{job.status.replaceAll('_', ' ')}</span></article>{:else}<p class="empty">No recent automation work.</p>{/each}</section>
			<section class="panel"><header><div><p class="eyebrow">Integrations</p><h2>Connection readiness</h2></div><a href="/admin/settings">Settings →</a></header>{#each data.integrations as integration (integration.id)}<article class="line"><div><strong>{integration.display_name}</strong><small>{integration.detail ?? 'No detail available'}</small></div><span class="badge {integration.status}">{integration.status.replaceAll('_', ' ')}</span></article>{/each}</section>
			<section class="panel"><header><div><p class="eyebrow">Security</p><h2>Accountability</h2></div><a href="/admin/audit">Audit log →</a></header><div class="team">{data.team.length} platform member{data.team.length === 1 ? '' : 's'} with control-plane access.</div>{#each data.activity.slice(0, 4) as item (item.id)}<article class="line"><div><strong>{item.action.replaceAll('_', ' ')}</strong><small>{item.organizations?.[0]?.name ?? 'Platform'} · {new Date(item.created_at).toLocaleString()}</small></div></article>{/each}</section>
			<section class="panel"><header><div><p class="eyebrow">Feature controls</p><h2>Safe product rollout</h2></div><span class="count">{data.flags.length}</span></header>{#each data.flags as flag (flag.id)}<article class="line"><div><strong>{flag.name}</strong><small>{flag.flag_key} · {flag.description ?? 'No description'}</small></div><span class="badge {flag.active ? 'connected' : 'disabled'}">{flag.active ? 'active' : 'disabled'}</span></article>{/each}<form method="POST" action="?/setFeatureAssignment" class="flag-form"><select name="organization_id" required><option value="">Choose client</option>{#each data.organizations as organization (organization.id)}<option value={organization.id}>{organization.name}</option>{/each}</select><select name="feature_flag_id" required><option value="">Choose feature</option>{#each data.flags as flag (flag.id)}<option value={flag.id}>{flag.name}</option>{/each}</select><label><input name="enabled" type="checkbox" checked /> Enable for client</label><button type="submit">Save allocation</button></form><form method="POST" action="?/createFeatureFlag" class="flag-form"><input name="name" required placeholder="Feature name" /><input name="flag_key" required placeholder="feature_key" /><input name="description" placeholder="Optional description" /><label><input name="enabled_by_default" type="checkbox" /> Default on</label><button type="submit">Add feature</button></form></section>
		</div>
	{/if}
</AdminChrome>

<style>
	.eyebrow{color:#7b9588;font-size:10px;font-weight:700;letter-spacing:.16em;margin:0 0 9px;text-transform:uppercase}.heading{margin-bottom:26px}.heading h1{font-size:clamp(38px,5vw,60px);letter-spacing:-.08em;line-height:.95;margin:0 0 13px}.heading h1 span{color:var(--musha-lime)}.heading p:not(.eyebrow){color:#718a7e;font-size:13px;margin:0;max-width:680px}.notice{background:#e6f2e6;border-radius:7px;color:#39704c;font-size:12px;margin:0 0 16px;padding:11px 13px}.notice.failure{background:#fae9e5;color:#955549}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.metrics div,.panel{background:#fff;border:1px solid #e4ebe4;border-radius:10px}.metrics div{padding:17px}.metrics span,.metrics strong{display:block}.metrics span{color:#81978b;font-size:10px}.metrics strong{color:#234d3e;font-size:26px;letter-spacing:-.06em;margin-top:6px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.panel{overflow:hidden}.panel.wide{grid-column:1/-1}.panel header{align-items:flex-start;border-bottom:1px solid #edf2ed;display:flex;justify-content:space-between;padding:20px}.panel h2{font-size:19px;letter-spacing:-.05em;margin:0}.panel header a{color:#487462;font-size:11px;text-decoration:none}.count,.badge{background:#edf4dc;border-radius:99px;color:#668a6d;font-size:10px;padding:6px 8px;white-space:nowrap}.line{align-items:flex-start;border-bottom:1px solid #edf2ed;display:flex;gap:10px;justify-content:space-between;padding:12px 20px}.line strong,.line small{display:block}.line strong{color:#345b4b;font-size:11px;text-transform:capitalize}.line small{color:#91a198;font-size:9px;line-height:1.45;margin-top:3px}.badge.failed,.badge.attention,.badge.at_risk{background:#fae9e5;color:#9a5548}.badge.queued,.badge.processing,.badge.watch{background:#fff4dc;color:#966c26}.empty,.team{color:#81958b;font-size:11px;padding:20px}.success-row{align-items:end;border-bottom:1px solid #edf2ed;display:grid;gap:8px;grid-template-columns:1.2fr repeat(4,.75fr) 1.5fr auto;padding:12px 20px}.success-row strong,.success-row small{display:block}.success-row strong{color:#345b4b;font-size:11px}.success-row small{color:#91a198;font-size:9px;margin-top:3px;text-transform:capitalize}label{color:#557568;display:grid;font-size:9px;font-weight:700;gap:4px}input,select{border:1px solid #dfe9e1;border-radius:6px;box-sizing:border-box;color:#345b4b;font:inherit;font-size:10px;padding:8px;width:100%}button{background:var(--musha-deep);border:0;border-radius:6px;color:#fff;cursor:pointer;font:inherit;font-size:10px;font-weight:700;padding:9px}.flag-form{display:grid;gap:7px;padding:14px 20px}.flag-form label{align-items:center;display:flex}.flag-form label input{width:auto}@media(max-width:1000px){.metrics{grid-template-columns:repeat(3,1fr)}.success-row{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.metrics,.grid,.success-row{grid-template-columns:1fr}.panel.wide{grid-column:auto}}
</style>
